### ISSUE TITLE
记录重复问题和一个疑问

### ISSUE THREAD

**Issue by likfe** [2017398956/packet-capture#1]
1. 首页-记录：读取完文件后 `data.add()` 之前忘了 `clear()` 了，导致每次刷新都加载一遍文件列表，重复了。
2. 有考虑支持HTTPS抓包嘛？毕竟现在有些量级的 APP 基本都是 HTTPS 的请求了。

**Comment by 2017398956** [comment]
1.最近忙没提交代码，你试试新的；还是这样的话，截下图看看
2.打算支持https，不过 Android7.0 不信任用户证书了，即使支持后也不一定能用

**Comment by likfe** [comment]
> 1.最近忙没提交代码，你试试新的；还是这样的话，截下图看看
> 2.打算支持https，不过 Android7.0 不信任用户证书了，即使支持后也不一定能用

嗯。Android 7.0 不信任用户证书这个问题，需要使用者想办法来解决，目前已知的方案可以参考 httpcanary。

毕竟这个项目是 Android 的抓包工具，随着时间的推移，必然大多数的 APP 会都上 HTTPS，从以后的发展来看，这可能是本项目的一个核心的基础功能。个人建议支持 HTTPS 尽快提上日程。
