### ISSUE TITLE
No Internet After VPN Successfully Connected

### ISSUE THREAD

**Issue by unsa1nted** [2017398956/packet-capture#2]
Hi, i appreciate it about your project.

But i have some problem in my project...

1. I have success connect the VPN, but after i connected to the VPN , my internet in emulator is going down ( Not working )
2. I try to disconnect the VPN, the internet is working again.

Any issue for this ? I use LDPlayer for my Emulator.

Thank you!

**Comment by 2017398956** [comment]
This project currently supports only IPV4.

**Comment by unsa1nted** [comment]
> This project currently supports only IPV4.

Before i try in office it's work, but today i've try in home doesn't work. Why ? I think LDPlayer is using IPv4 not IPv6 .. Cmiiw

Any suggestion ?

**Comment by 2017398956** [comment]
Are all apps cannot connected to the Internet?

**Comment by unsa1nted** [comment]
> Are all apps cannot connected to the Internet?

Yup that is correct, if i disconnect the VPN , the internet is connected again. I don't know why this is happening so confuse.

Maybe you have idea?

**Comment by 2017398956** [comment]
I'll see if I can recreate your situation.This maytake a few days.

**Comment by 2017398956** [comment]
This is useless code.
I had tried with LDPlayer on three PC, All are in working order.🤷‍♂️

**Comment by unsa1nted** [comment]
Then why in my LDPlayer can't capture anything? I have try to disabled Firewall & Still Nothing happend to Capture.

Btw, do you have telegram?

**Comment by 2017398956** [comment]
I don't have telegram.
You can have a test on some others emulator or a real phone.
